### ISSUE TITLE
Centering of figure captions

### ISSUE THREAD

**Issue by vbollen** [seanmossman/WSU_ThesisTemplate_LaTeX#5]
If one adds a short caption (less than one line long), the caption is centered on the figure instead of flush to the left.

**Comment by seanmossman** [comment]
In the caption package add the option singlelinecheck=off to disable centered short captions
http://tex.stackexchange.com/questions/120411/raggedright-and-caption-package
I think within the LaTeX community, that behavior might be considered a feature, not a bug, but my captions are always huge so I haven't seen that problem.

**Comment by vbollen** [comment]
Thanks! I ran into into for my large pictures where the caption ends up being on the next page and I have a short (Continued on the following page.) caption under the figure
